server:
  port: 6001
spring:
  application:
    name: zipkin
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#不配置会报错
management:
  metrics:
    web:
      server:
        auto-time-requests: false





