server:
  port: 8084
eureka:
  instance:
    hostname: localhost
    metadata-map:
      cluster: ribbon
    prefer-ip-address: true
    status-page-url: http://${eureka.instance.hostname}:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: consumer-ribbon2
swagger:
  enabled: true
  title: 消费者ribbon
  description: 消费者模块API
  base-package: com.test.consumerribbon.controller
  contact:
    name: salkwqpo
    email: 278202617@qq.com
    url: www.hbhtxx.com

