server:
  port: 4001
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: spring-admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  #链路跟踪
  zipkin:
    base-url: http://localhost:6001
  sleuth:
    sampler:
      probability: 1.0 #采样比例
  main:
    allow-bean-definition-overriding: true
